# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerCatalog', '0003_beer_beer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_type',
            field=models.IntegerField(choices=[(1, 'Lata'), (2, 'Latao'), (3, 'Garrafa'), (4, 'Litro')]),
        ),
    ]
