# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerCatalog', '0004_auto_20160922_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='market',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='beerCatalog.Market'),
            preserve_default=False,
        ),
    ]
