# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerCatalog', '0005_auto_20160922_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Market',
            new_name='Vendor',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='market',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='market_name',
            new_name='vendor_name',
        ),
    ]
