# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerCatalog', '0006_auto_20160922_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_type',
            field=models.CharField(choices=[('1', 'Lata'), ('2', 'Latao'), ('3', 'Garrafa'), ('4', 'Litro'), ('5', 'Garrafinha')], max_length=1),
        ),
    ]
